router:
  http.get:
    blogs.index:
      "/blogs": ~

    blogs.sole:
      "/blogs/{user_hid}":
        user_hid:
          match: /\d+/
          type: 'integer'

    blogs.sole.unsubscribe:
      "/blogs/{user_hid}/unsubscribe":
        user_hid:
          match: /\d+/
          type: 'integer'

    blogs.entry:
      "/blogs/{user_hid}/{entry_hid}":
        user_hid:
          match: /\d+/
          type: 'integer'
        entry_hid:
          match: /\d+/
          type: 'integer'

    blogs.entry.unsubscribe:
      "/blogs/{user_hid}/{entry_hid}/unsubscribe":
        user_hid:
          match: /\d+/
          type: 'integer'
        entry_hid:
          match: /\d+/
          type: 'integer'

    blogs.entry.mute:
      "/blogs/{user_hid}/{entry_hid}/mute":
        user_hid:
          match: /\d+/
          type: 'integer'
        entry_hid:
          match: /\d+/
          type: 'integer'

    search.blogs_sole:
      "/search_blogs_sole": ~
